
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var k={},m;for(m in g)g.hasOwnProperty(m)&&(k[m]=g[m]);var n=[],aa="./this.program";function v(a,b){throw b;}var ba=!1,y=!1,z=!1,ca=!1;ba="object"===typeof window;y="function"===typeof importScripts;z="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!ba&&!z&&!y;var A="",da,ea,C,fa,ja;
if(z)A=y?require("path").dirname(A)+"/":__dirname+"/",da=function(a,b){fa||(fa=require("fs"));ja||(ja=require("path"));a=ja.normalize(a);return fa.readFileSync(a,b?null:"utf8")},C=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),n=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof ka))throw a;}),process.on("unhandledRejection",
D),v=function(a){process.exit(a)},g.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),C=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?n=scriptArgs:"undefined"!=typeof arguments&&(n=arguments),"function"===typeof quit&&(v=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(ba||y)y?A=self.location.href:"undefined"!==typeof document&&document.currentScript&&(A=document.currentScript.src),A=0!==A.indexOf("blob:")?A.substr(0,A.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},y&&(C=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
ea=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var la=g.print||console.log.bind(console),F=g.printErr||console.warn.bind(console);for(m in k)k.hasOwnProperty(m)&&(g[m]=k[m]);k=null;g.arguments&&(n=g.arguments);g.thisProgram&&(aa=g.thisProgram);g.quit&&(v=g.quit);var G;g.wasmBinary&&(G=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!1;
"object"!==typeof WebAssembly&&D("no native wasm support detected");var ma,H=!1;function assert(a,b){a||D("Assertion failed: "+b)}var na="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function I(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&na)return na.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var e=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|e);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|e<<6|l:(f&7)<<18|e<<12|l<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function pa(a){return a?I(qa,a,void 0):""}
function ra(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var e=0;e<a.length;++e){var l=a.charCodeAt(e);if(55296<=l&&57343>=l){var q=a.charCodeAt(++e);l=65536+((l&1023)<<10)|q&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=ua(b);ra(a,J,c,b);return c}var va,J,qa,wa,K,xa=[],za=[],Aa=[],Ba=[],Ca=[];function Da(){var a=g.preRun.shift();xa.unshift(a)}var L=0,Ea=null,Fa=null;g.preloadedImages={};g.preloadedAudios={};
function D(a){if(g.onAbort)g.onAbort(a);F(a);H=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ga(){return M.startsWith("data:application/octet-stream;base64,")}var M="webm-muxer.wasm";if(!Ga()){var Ha=M;M=g.locateFile?g.locateFile(Ha,A):A+Ha}function Ia(){var a=M;try{if(a==M&&G)return new Uint8Array(G);if(C)return C(a);throw"both async and sync fetching of the wasm failed";}catch(b){D(b)}}
function Ja(){if(!G&&(ba||y)){if("function"===typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ia()});if(ea)return new Promise(function(a,b){ea(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ia()})}var N,Ka;
function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.ja;"number"===typeof c?void 0===b.$?Ma.call(null,c):Na.apply(null,[c,b.$]):c(void 0===b.$?null:b.$)}}}function Oa(a){this.X=a-16;this.Ka=function(b){K[this.X+8>>2]=b};this.Ha=function(b){K[this.X+0>>2]=b};this.Ia=function(){K[this.X+4>>2]=0};this.Ga=function(){J[this.X+12>>0]=0};this.Ja=function(){J[this.X+13>>0]=0};this.Aa=function(b,c){this.Ka(b);this.Ha(c);this.Ia();this.Ga();this.Ja()}}var Pa=0;
function Qa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Ra(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Qa(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Sa(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Ta(a){if("/"===a)return"/";a=Ra(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Ua(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}if(z)try{var b=require("crypto");return function(){return b.randomBytes(1)[0]}}catch(c){}return function(){D("randomDevice")}}
function Va(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Qa(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],W:b};Ya(a,Za)}
var Za={open:function(a){var b=Wa[a.node.rdev];if(!b)throw new O(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.W.flush(a.tty)},flush:function(a){a.tty.W.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.W.ua)throw new O(60);for(var f=0,e=0;e<d;e++){try{var l=a.tty.W.ua(a.tty)}catch(q){throw new O(29);}if(void 0===l&&0===f)throw new O(6);if(null===l||void 0===l)break;f++;b[c+e]=l}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.W.ma)throw new O(60);try{for(var f=
0;f<d;f++)a.tty.W.ma(a.tty,b[c+f])}catch(e){throw new O(29);}d&&(a.node.timestamp=Date.now());return f}},ab={ua:function(a){if(!a.input.length){var b=null;if(z){var c=Buffer.V?Buffer.V(256):new Buffer(256),d=0;try{d=fa.readSync(process.stdin.fd,c,0,256,null)}catch(f){if(f.toString().includes("EOF"))d=0;else throw f;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&
(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=$a(b,!0)}return a.input.shift()},ma:function(a,b){null===b||10===b?(la(I(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(la(I(a.output,0)),a.output=[])}},bb={ma:function(a,b){null===b||10===b?(F(I(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(F(I(a.output,0)),a.output=[])}},P={O:null,S:function(){return P.createNode(null,"/",16895,0)},createNode:function(a,
b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new O(63);P.O||(P.O={dir:{node:{T:P.K.T,P:P.K.P,lookup:P.K.lookup,aa:P.K.aa,rename:P.K.rename,unlink:P.K.unlink,rmdir:P.K.rmdir,readdir:P.K.readdir,symlink:P.K.symlink},stream:{U:P.L.U}},file:{node:{T:P.K.T,P:P.K.P},stream:{U:P.L.U,read:P.L.read,write:P.L.write,pa:P.L.pa,va:P.L.va,xa:P.L.xa}},link:{node:{T:P.K.T,P:P.K.P,readlink:P.K.readlink},stream:{}},qa:{node:{T:P.K.T,P:P.K.P},stream:cb}});c=db(a,b,c,d);16384===(c.mode&61440)?(c.K=P.O.dir.node,
c.L=P.O.dir.stream,c.J={}):32768===(c.mode&61440)?(c.K=P.O.file.node,c.L=P.O.file.stream,c.M=0,c.J=null):40960===(c.mode&61440)?(c.K=P.O.link.node,c.L=P.O.link.stream):8192===(c.mode&61440)&&(c.K=P.O.qa.node,c.L=P.O.qa.stream);c.timestamp=Date.now();a&&(a.J[b]=c,a.timestamp=c.timestamp);return c},Ra:function(a){return a.J?a.J.subarray?a.J.subarray(0,a.M):new Uint8Array(a.J):new Uint8Array(0)},ra:function(a,b){var c=a.J?a.J.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,
256)),c=a.J,a.J=new Uint8Array(b),0<a.M&&a.J.set(c.subarray(0,a.M),0))},Ea:function(a,b){if(a.M!=b)if(0==b)a.J=null,a.M=0;else{var c=a.J;a.J=new Uint8Array(b);c&&a.J.set(c.subarray(0,Math.min(b,a.M)));a.M=b}},K:{T:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.M:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);
b.ctime=new Date(a.timestamp);b.za=4096;b.blocks=Math.ceil(b.size/b.za);return b},P:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&P.Ea(a,b.size)},lookup:function(){throw eb[44];},aa:function(a,b,c,d){return P.createNode(a,b,c,d)},rename:function(a,b,c){if(16384===(a.mode&61440)){try{var d=fb(b,c)}catch(e){}if(d)for(var f in d.J)throw new O(55);}delete a.parent.J[a.name];a.parent.timestamp=Date.now();a.name=c;b.J[c]=a;b.timestamp=a.parent.timestamp;
a.parent=b},unlink:function(a,b){delete a.J[b];a.timestamp=Date.now()},rmdir:function(a,b){var c=fb(a,b),d;for(d in c.J)throw new O(55);delete a.J[b];a.timestamp=Date.now()},readdir:function(a){var b=[".",".."],c;for(c in a.J)a.J.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=P.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new O(28);return a.link}},L:{read:function(a,b,c,d,f){var e=a.node.J;if(f>=a.node.M)return 0;a=Math.min(a.node.M-
f,d);if(8<a&&e.subarray)b.set(e.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=e[f+d];return a},write:function(a,b,c,d,f,e){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.J||a.J.subarray)){if(e)return a.J=b.subarray(c,c+d),a.M=d;if(0===a.M&&0===f)return a.J=b.slice(c,c+d),a.M=d;if(f+d<=a.M)return a.J.set(b.subarray(c,c+d),f),d}P.ra(a,f+d);if(a.J.subarray&&b.subarray)a.J.set(b.subarray(c,c+d),f);else for(e=0;e<d;e++)a.J[f+e]=b[c+e];a.M=Math.max(a.M,f+d);return d},U:function(a,b,
c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.M);if(0>b)throw new O(28);return b},pa:function(a,b,c){P.ra(a.node,b+c);a.node.M=Math.max(a.node.M,b+c)},va:function(a,b,c,d,f,e){if(0!==b)throw new O(28);if(32768!==(a.node.mode&61440))throw new O(43);a=a.node.J;if(e&2||a.buffer!==va){if(0<d||d+c<a.length)a.subarray?a=a.subarray(d,d+c):a=Array.prototype.slice.call(a,d,d+c);d=!0;e=16384*Math.ceil(c/16384);for(b=gb(e);c<e;)J[b+c++]=0;c=b;if(!c)throw new O(48);J.set(a,c)}else d=!1,
c=a.byteOffset;return{X:c,Qa:d}},xa:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new O(43);if(f&2)return 0;P.L.write(a,b,0,d,c,!1);return 0}}},hb=null,ib={},Q=[],jb=1,kb=null,lb=!0,mb={},O=null,eb={};
function R(a,b){a=Va("/",a);b=b||{};if(!a)return{path:"",node:null};var c={ta:!0,na:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.na)throw new O(32);a=Qa(a.split("/").filter(function(l){return!!l}),!1);var f=hb;c="/";for(d=0;d<a.length;d++){var e=d===a.length-1;if(e&&b.parent)break;f=fb(f,a[d]);c=Ra(c+"/"+a[d]);f.ba&&(!e||e&&b.ta)&&(f=f.ba.root);if(!e||b.sa)for(e=0;40960===(f.mode&61440);)if(f=nb(c),c=Va(Sa(c),f),f=R(c,{na:b.na}).node,40<e++)throw new O(32);}return{path:c,node:f}}
function ob(a){for(var b;;){if(a===a.parent)return a=a.S.wa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function pb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%kb.length}function fb(a,b){var c;if(c=(c=qb(a,"x"))?c:a.K.lookup?0:2)throw new O(c,a);for(c=kb[pb(a.id,b)];c;c=c.Da){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.K.lookup(a,b)}
function db(a,b,c,d){a=new rb(a,b,c,d);b=pb(a.parent.id,a.name);a.Da=kb[b];return kb[b]=a}var sb={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function tb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function qb(a,b){if(lb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function ub(a,b){try{return fb(a,b),20}catch(c){}return qb(a,"wx")}
function vb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Q[a])return a;throw new O(33);}function wb(a,b){xb||(xb=function(){},xb.prototype={});var c=new xb,d;for(d in a)c[d]=a[d];a=c;b=vb(b);a.fd=b;return Q[b]=a}var cb={open:function(a){a.L=ib[a.node.rdev].L;a.L.open&&a.L.open(a)},U:function(){throw new O(70);}};function Ya(a,b){ib[a]={L:b}}
function yb(a,b){var c="/"===b,d=!b;if(c&&hb)throw new O(10);if(!c&&!d){var f=R(b,{ta:!1});b=f.path;f=f.node;if(f.ba)throw new O(10);if(16384!==(f.mode&61440))throw new O(54);}b={type:a,Sa:{},wa:b,Ca:[]};a=a.S(b);a.S=b;b.root=a;c?hb=a:f&&(f.ba=b,f.S&&f.S.Ca.push(b))}function zb(a,b,c){var d=R(a,{parent:!0}).node;a=Ta(a);if(!a||"."===a||".."===a)throw new O(28);var f=ub(d,a);if(f)throw new O(f);if(!d.K.aa)throw new O(63);return d.K.aa(d,a,b,c)}function S(a){return zb(a,16895,0)}
function Ab(a,b,c){"undefined"===typeof c&&(c=b,b=438);zb(a,b|8192,c)}function Bb(a,b){if(!Va(a))throw new O(44);var c=R(b,{parent:!0}).node;if(!c)throw new O(44);b=Ta(b);var d=ub(c,b);if(d)throw new O(d);if(!c.K.symlink)throw new O(63);c.K.symlink(c,b,a)}function nb(a){a=R(a).node;if(!a)throw new O(44);if(!a.K.readlink)throw new O(28);return Va(ob(a.parent),a.K.readlink(a))}
function Cb(a,b,c,d){if(""===a)throw new O(44);if("string"===typeof b){var f=sb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var e=a;else{a=Ra(a);try{e=R(a,{sa:!(b&131072)}).node}catch(l){}}f=!1;if(b&64)if(e){if(b&128)throw new O(20);}else e=zb(a,c,0),f=!0;if(!e)throw new O(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new O(54);if(!f&&(c=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==tb(b)||b&512)?31:qb(e,tb(b)):44))throw new O(c);if(b&512){c=e;c="string"===typeof c?R(c,{sa:!0}).node:c;if(!c.K.P)throw new O(63);if(16384===(c.mode&61440))throw new O(31);if(32768!==(c.mode&61440))throw new O(28);if(f=qb(c,"w"))throw new O(f);c.K.P(c,{size:0,timestamp:Date.now()})}b&=-131713;d=wb({node:e,path:ob(e),flags:b,seekable:!0,position:0,L:e.L,Pa:[],error:!1},d);d.L.open&&d.L.open(d);!g.logReadFiles||b&1||(Db||(Db={}),a in Db||(Db[a]=1,F("FS.trackingDelegate error on read file: "+
a)));try{mb.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),mb.onOpenFile(a,e))}catch(l){F("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Eb(a){if(null===a.fd)throw new O(8);a.ka&&(a.ka=null);try{a.L.close&&a.L.close(a)}catch(b){throw b;}finally{Q[a.fd]=null}a.fd=null}function Fb(a,b,c){if(null===a.fd)throw new O(8);if(!a.seekable||!a.L.U)throw new O(70);if(0!=c&&1!=c&&2!=c)throw new O(28);a.position=a.L.U(a,b,c);a.Pa=[]}
function Gb(){O||(O=function(a,b){this.node=b;this.Fa=function(c){this.R=c};this.Fa(a);this.message="FS error"},O.prototype=Error(),O.prototype.constructor=O,[44].forEach(function(a){eb[a]=new O(a);eb[a].stack="<generic error, no stack>"}))}var Hb;function Jb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Kb(a,b,c){a=Ra("/dev/"+a);var d=Jb(!!b,!!c);Lb||(Lb=64);var f=Lb++<<8|0;Ya(f,{open:function(e){e.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(e,l,q,w){for(var t=0,r=0;r<w;r++){try{var x=b()}catch(E){throw new O(29);}if(void 0===x&&0===t)throw new O(6);if(null===x||void 0===x)break;t++;l[q+r]=x}t&&(e.node.timestamp=Date.now());return t},write:function(e,l,q,w){for(var t=0;t<w;t++)try{c(l[q+t])}catch(r){throw new O(29);}w&&(e.node.timestamp=Date.now());return t}});
Ab(a,d,f)}var Lb,T={},xb,Db,Mb=void 0;function U(){Mb+=4;return K[Mb-4>>2]}function W(a){a=Q[a];if(!a)throw new O(8);return a}var Nb={};function Ob(){if(!Pb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in Nb)a[b]=Nb[b];var c=[];for(b in a)c.push(b+"="+a[b]);Pb=c}return Pb}var Pb;
function Qb(a){return 0===a%4&&(0!==a%100||0===a%400)}function Rb(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Sb=[31,29,31,30,31,30,31,31,30,31,30,31],Tb=[31,28,31,30,31,30,31,31,30,31,30,31];function Ub(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Qb(a.getFullYear())?Sb:Tb)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Vb(a,b,c,d){function f(h,p,u){for(h="number"===typeof h?h.toString():h||"";h.length<p;)h=u[0]+h;return h}function e(h,p){return f(h,p,"0")}function l(h,p){function u(Ib){return 0>Ib?-1:0<Ib?1:0}var B;0===(B=u(h.getFullYear()-p.getFullYear()))&&0===(B=u(h.getMonth()-p.getMonth()))&&(B=u(h.getDate()-p.getDate()));return B}function q(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function w(h){h=Ub(new Date(h.N+1900,0,1),h.fa);var p=new Date(h.getFullYear()+1,0,4),u=q(new Date(h.getFullYear(),0,4));p=q(p);return 0>=l(u,h)?0>=l(p,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var t=K[d+40>>2];d={Na:K[d>>2],Ma:K[d+4>>2],da:K[d+8>>2],Z:K[d+12>>2],Y:K[d+16>>2],N:K[d+20>>2],ea:K[d+24>>2],fa:K[d+28>>2],Ta:K[d+32>>2],La:K[d+36>>
2],Oa:t?pa(t):""};c=pa(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var r in t)c=c.replace(new RegExp(r,"g"),t[r]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
E="January February March April May June July August September October November December".split(" ");t={"%a":function(h){return x[h.ea].substring(0,3)},"%A":function(h){return x[h.ea]},"%b":function(h){return E[h.Y].substring(0,3)},"%B":function(h){return E[h.Y]},"%C":function(h){return e((h.N+1900)/100|0,2)},"%d":function(h){return e(h.Z,2)},"%e":function(h){return f(h.Z,2," ")},"%g":function(h){return w(h).toString().substring(2)},"%G":function(h){return w(h)},"%H":function(h){return e(h.da,2)},
"%I":function(h){h=h.da;0==h?h=12:12<h&&(h-=12);return e(h,2)},"%j":function(h){return e(h.Z+Rb(Qb(h.N+1900)?Sb:Tb,h.Y-1),3)},"%m":function(h){return e(h.Y+1,2)},"%M":function(h){return e(h.Ma,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.da&&12>h.da?"AM":"PM"},"%S":function(h){return e(h.Na,2)},"%t":function(){return"\t"},"%u":function(h){return h.ea||7},"%U":function(h){var p=new Date(h.N+1900,0,1),u=0===p.getDay()?p:Ub(p,7-p.getDay());h=new Date(h.N+1900,h.Y,h.Z);return 0>l(u,h)?
e(Math.ceil((31-u.getDate()+(Rb(Qb(h.getFullYear())?Sb:Tb,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(u,p)?"01":"00"},"%V":function(h){var p=new Date(h.N+1901,0,4),u=q(new Date(h.N+1900,0,4));p=q(p);var B=Ub(new Date(h.N+1900,0,1),h.fa);return 0>l(B,u)?"53":0>=l(p,B)?"01":e(Math.ceil((u.getFullYear()<h.N+1900?h.fa+32-u.getDate():h.fa+1-u.getDate())/7),2)},"%w":function(h){return h.ea},"%W":function(h){var p=new Date(h.N,0,1),u=1===p.getDay()?p:Ub(p,0===p.getDay()?1:7-p.getDay()+1);h=new Date(h.N+
1900,h.Y,h.Z);return 0>l(u,h)?e(Math.ceil((31-u.getDate()+(Rb(Qb(h.getFullYear())?Sb:Tb,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(u,p)?"01":"00"},"%y":function(h){return(h.N+1900).toString().substring(2)},"%Y":function(h){return h.N+1900},"%z":function(h){h=h.La;var p=0<=h;h=Math.abs(h)/60;return(p?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.Oa},"%%":function(){return"%"}};for(r in t)c.includes(r)&&(c=c.replace(new RegExp(r,"g"),t[r](d)));r=$a(c,!1);if(r.length>
b)return 0;J.set(r,a);return r.length-1}function Wb(a){try{a()}catch(b){D(b)}}var X=0,Y=null,Xb=0,Yb=[],Zb={},$b={},ac=0,bc=null,cc=[],dc=[];function ec(a){var b={},c;for(c in a)(function(d){var f=a[d];b[d]="function"===typeof f?function(){Yb.push(d);try{return f.apply(null,arguments)}finally{if(H)return;var e=Yb.pop();assert(e===d);Y&&1===X&&0===Yb.length&&(X=0,Wb(g._asyncify_stop_unwind),"undefined"!==typeof Fibers&&Fibers.Ua(),bc&&(bc(),bc=null))}}:f})(c);return b}
function fc(){var a=gb(4108),b=a+12;K[a>>2]=b;K[a+4>>2]=b+4096;b=Yb[0];var c=Zb[b];void 0===c&&(c=ac++,Zb[b]=c,$b[c]=b);K[a+8>>2]=c;return a}
function hc(a){if(!H){noExitRuntime=!0;if(0===X){var b=!1,c=!1;a(function(d){if(!H&&(Xb=d||0,b=!0,c)){X=2;Wb(function(){g._asyncify_start_rewind(Y)});"undefined"!==typeof Z&&Z.la.ja&&Z.la.resume();var f=(0,g.asm[$b[K[Y+8>>2]]])();Y||(d=cc,cc=[],d.forEach(function(e){e(f)}))}});c=!0;b||(X=1,Y=fc(),Wb(function(){g._asyncify_start_unwind(Y)}),"undefined"!==typeof Z&&Z.la.ja&&Z.la.pause())}else 2===X?(X=0,Wb(g._asyncify_stop_rewind),ic(Y),Y=null,dc.forEach(function(d){d()})):D("invalid state: "+X);return Xb}}
function rb(a,b,c,d){a||(a=this);this.parent=a;this.S=a.S;this.ba=null;this.id=jb++;this.name=b;this.mode=c;this.K={};this.L={};this.rdev=d}Object.defineProperties(rb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Gb();kb=Array(4096);yb(P,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");Ya(259,{read:function(){return 0},write:function(b,c,d,f){return f}});Ab("/dev/null",259);Xa(1280,ab);Xa(1536,bb);Ab("/dev/tty",1280);Ab("/dev/tty1",1536);var a=Ua();Kb("random",a);Kb("urandom",a);S("/dev/shm");S("/dev/shm/tmp")})();
(function(){S("/proc");var a=S("/proc/self");S("/proc/self/fd");yb({S:function(){var b=db(a,"fd",16895,73);b.K={lookup:function(c,d){var f=Q[+d];if(!f)throw new O(8);c={parent:null,S:{wa:"fake"},K:{readlink:function(){return f.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var Z;function $a(a,b){var c=Array(sa(a)+1);a=ra(a,c,0,c.length);b&&(c.length=a);return c}
var kc={k:function(a){return gb(a+16)+16},a:function(a,b){Ba.unshift({ja:a,$:b})},j:function(a,b,c){(new Oa(a)).Aa(b,c);Pa++;throw a;},c:function(a,b,c){Mb=c;try{var d=W(a);switch(b){case 0:var f=U();return 0>f?-28:Cb(d.path,d.flags,0,f).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return f=U(),d.flags|=f,0;case 12:return f=U(),wa[f+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return K[jc()>>2]=28,-1;default:return-28}}catch(e){return"undefined"!==typeof T&&e instanceof
O||D(e),-e.R}},h:function(a,b,c){Mb=c;try{var d=W(a);switch(b){case 21509:case 21505:return d.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return d.tty?0:-59;case 21519:if(!d.tty)return-59;var f=U();return K[f>>2]=0;case 21520:return d.tty?-28:-59;case 21531:a=f=U();if(!d.L.Ba)throw new O(59);return d.L.Ba(d,b,a);case 21523:return d.tty?0:-59;case 21524:return d.tty?0:-59;default:D("bad ioctl syscall "+b)}}catch(e){return"undefined"!==typeof T&&e instanceof O||D(e),
-e.R}},i:function(a,b,c){Mb=c;try{var d=pa(a),f=c?U():0;return Cb(d,b,f).fd}catch(e){return"undefined"!==typeof T&&e instanceof O||D(e),-e.R}},d:function(){D()},n:function(a){self.postMessage({type:"exit",code:a});return a},o:function(a,b,c){qa.copyWithin(a,b,b+c)},b:function(a,b){self.ya||(self.ha=[],self.V=null,self.ga=null,self.ia=null,self.oa=function(){if(0<self.ha.length){var c=self.ha.shift();let d=-1;c.length<=self.ia&&(d=c.length,qa.set(c,self.ga));c=self.V;self.V=null;self.ga=null;self.ia=
null;c(d)}},self.onmessage=function(c){c=c.data;switch(c.type){case "stream-data":self.ha.push(new Uint8Array(c.data)),self.V&&self.oa()}},self.postMessage({type:"start-stream"}),self.ya=!0);return hc(c=>{if(0>=b)return c(0);self.V=c;self.ga=a;self.ia=b;self.oa()})},p:function(){D("OOM")},t:function(a,b){a=qa.slice(a,a+b).buffer;self.postMessage({type:"muxed-data",data:a},[a]);return b},r:function(a,b){try{var c=0;Ob().forEach(function(d,f){var e=b+c;f=K[a+4*f>>2]=e;for(e=0;e<d.length;++e)J[f++>>
0]=d.charCodeAt(e);J[f>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof T&&d instanceof O||D(d),d.R}},s:function(a,b){try{var c=Ob();K[a>>2]=c.length;var d=0;c.forEach(function(f){d+=f.length+1});K[b>>2]=d;return 0}catch(f){return"undefined"!==typeof T&&f instanceof O||D(f),f.R}},f:function(a){try{var b=W(a);Eb(b);return 0}catch(c){return"undefined"!==typeof T&&c instanceof O||D(c),c.R}},g:function(a,b,c,d){try{a:{for(var f=W(a),e=a=0;e<c;e++){var l=K[b+(8*e+4)>>2],q=f,w=K[b+8*e>>
2],t=l,r=void 0,x=J;if(0>t||0>r)throw new O(28);if(null===q.fd)throw new O(8);if(1===(q.flags&2097155))throw new O(8);if(16384===(q.node.mode&61440))throw new O(31);if(!q.L.read)throw new O(28);var E="undefined"!==typeof r;if(!E)r=q.position;else if(!q.seekable)throw new O(70);var h=q.L.read(q,x,w,t,r);E||(q.position+=h);var p=h;if(0>p){var u=-1;break a}a+=p;if(p<l)break}u=a}K[d>>2]=u;return 0}catch(B){return"undefined"!==typeof T&&B instanceof O||D(B),B.R}},m:function(a,b,c,d,f){try{var e=W(a);a=
4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Fb(e,a,d);Ka=[e.position>>>0,(N=e.position,1<=+Math.abs(N)?0<N?(Math.min(+Math.floor(N/4294967296),4294967295)|0)>>>0:~~+Math.ceil((N-+(~~N>>>0))/4294967296)>>>0:0)];K[f>>2]=Ka[0];K[f+4>>2]=Ka[1];e.ka&&0===a&&0===d&&(e.ka=null);return 0}catch(l){return"undefined"!==typeof T&&l instanceof O||D(l),l.R}},e:function(a,b,c,d){try{a:{for(var f=W(a),e=a=0;e<c;e++){var l=f,q=K[b+8*e>>2],w=K[b+(8*e+4)>>2],t=void 0,r=J;if(0>w||0>t)throw new O(28);
if(null===l.fd)throw new O(8);if(0===(l.flags&2097155))throw new O(8);if(16384===(l.node.mode&61440))throw new O(31);if(!l.L.write)throw new O(28);l.seekable&&l.flags&1024&&Fb(l,0,2);var x="undefined"!==typeof t;if(!x)t=l.position;else if(!l.seekable)throw new O(70);var E=l.L.write(l,r,q,w,t,void 0);x||(l.position+=E);try{if(l.path&&mb.onWriteToFile)mb.onWriteToFile(l.path)}catch(u){F("FS.trackingDelegate['onWriteToFile']('"+l.path+"') threw an exception: "+u.message)}var h=E;if(0>h){var p=-1;break a}a+=
h}p=a}K[d>>2]=p;return 0}catch(u){return"undefined"!==typeof T&&u instanceof O||D(u),u.R}},q:function(a,b,c,d){return Vb(a,b,c,d)},l:function(a){var b=Date.now()/1E3|0;a&&(K[a>>2]=b);return b}};
(function(){function a(e){e=e.exports;e=ec(e);g.asm=e;ma=g.asm.u;va=e=ma.buffer;g.HEAP8=J=new Int8Array(e);g.HEAP16=wa=new Int16Array(e);g.HEAP32=K=new Int32Array(e);g.HEAPU8=qa=new Uint8Array(e);g.HEAPU16=new Uint16Array(e);g.HEAPU32=new Uint32Array(e);g.HEAPF32=new Float32Array(e);g.HEAPF64=new Float64Array(e);za.unshift(g.asm.v);L--;g.monitorRunDependencies&&g.monitorRunDependencies(L);0==L&&(null!==Ea&&(clearInterval(Ea),Ea=null),Fa&&(e=Fa,Fa=null,e()))}function b(e){a(e.instance)}function c(e){return Ja().then(function(l){return WebAssembly.instantiate(l,
d)}).then(e,function(l){F("failed to asynchronously prepare wasm: "+l);D(l)})}var d={a:kc};L++;g.monitorRunDependencies&&g.monitorRunDependencies(L);if(g.instantiateWasm)try{var f=g.instantiateWasm(d,a);return f=ec(f)}catch(e){return F("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return G||"function"!==typeof WebAssembly.instantiateStreaming||Ga()||M.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(l){F("wasm streaming compile failed: "+l);F("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.v).apply(null,arguments)};g._main=function(){return(g._main=g.asm.w).apply(null,arguments)};var jc=g.___errno_location=function(){return(jc=g.___errno_location=g.asm.y).apply(null,arguments)};g._fflush=function(){return(g._fflush=g.asm.z).apply(null,arguments)};
var ic=g._free=function(){return(ic=g._free=g.asm.A).apply(null,arguments)},gb=g._malloc=function(){return(gb=g._malloc=g.asm.B).apply(null,arguments)},ua=g.stackAlloc=function(){return(ua=g.stackAlloc=g.asm.C).apply(null,arguments)},Na=g.dynCall_vi=function(){return(Na=g.dynCall_vi=g.asm.D).apply(null,arguments)},Ma=g.dynCall_v=function(){return(Ma=g.dynCall_v=g.asm.E).apply(null,arguments)};g._asyncify_start_unwind=function(){return(g._asyncify_start_unwind=g.asm.F).apply(null,arguments)};
g._asyncify_stop_unwind=function(){return(g._asyncify_stop_unwind=g.asm.G).apply(null,arguments)};g._asyncify_start_rewind=function(){return(g._asyncify_start_rewind=g.asm.H).apply(null,arguments)};g._asyncify_stop_rewind=function(){return(g._asyncify_stop_rewind=g.asm.I).apply(null,arguments)};var lc;function ka(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Fa=function mc(){lc||nc();lc||(Fa=mc)};
function nc(a){function b(){if(!lc&&(lc=!0,g.calledRun=!0,!H)){g.noFSInit||Hb||(Hb=!0,Gb(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?Kb("stdin",g.stdin):Bb("/dev/tty","/dev/stdin"),g.stdout?Kb("stdout",null,g.stdout):Bb("/dev/tty","/dev/stdout"),g.stderr?Kb("stderr",null,g.stderr):Bb("/dev/tty1","/dev/stderr"),Cb("/dev/stdin",0),Cb("/dev/stdout",1),Cb("/dev/stderr",1));La(za);lb=!1;La(Aa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(oc){var c=a,d=g._main;c=c||[];var f=c.length+
1,e=ua(4*(f+1));K[e>>2]=ta(aa);for(var l=1;l<f;l++)K[(e>>2)+l]=ta(c[l-1]);K[(e>>2)+f]=0;try{var q=d(f,e);if(!(noExitRuntime||noExitRuntime&&0===q)){if(!noExitRuntime){La(Ba);Hb=!1;var w=g._fflush;w&&w(0);for(c=0;c<Q.length;c++){var t=Q[c];t&&Eb(t)}if(g.onExit)g.onExit(q);H=!0}v(q,new ka(q))}}catch(r){r instanceof ka||"unwind"==r||((q=r)&&"object"===typeof r&&r.stack&&(q=[r,r.stack]),F("exception thrown: "+q),v(1,r))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)q=
g.postRun.shift(),Ca.unshift(q);La(Ca)}}a=a||n;if(!(0<L)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Da();La(xa);0<L||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=nc;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var oc=!0;g.noInitialRun&&(oc=!1);nc();
